[params]
  paginate = 5
  copyrightYears = "MMXXI - MMXXIV"
  enableBlogPost = true
  enableTOC = true
  subTitle = "Enthusiast & Sammler"
  me = "/images/me-200.png"
  monogram = "/images/cm.svg"
  monogramBlack = "/images/cm-black.svg"
  favicon_svg = "/images/cm.svg"
  copyrightlink = "https://christianmahnke.de"
  links = ['<a href="https://github.com/cmahnke" target="_blank" title="GitHub"><div class="link-image github"></div>GitHub</a>',
           '<a href="https://projektemacher.org/" target="_blank" title="Projektemacher"><img class="link-image projektemacher" alt="Projektemacher Logo" src="/images/laborant.svg">Projektemacher</a>',
           '<a href="https://orcid.org/0009-0003-1361-4159" target="_blank" title="ORCID"><div class="link-image orcid"></div>0009-0003-1361-4159</a>',
           '<a href="https://www.linkedin.com/in/cmahnke" target="_blank" title="LinkedIn"><div class="link-image linkedin"></div>LinkedIn</a>',
           '<a href="https://www.librarything.com/profile/cmahnke" target="_blank" title="Librarything"><div class="link-image librarything"></div>Librarything</a>',
           '<a href="https://www.instagram.com/projektemacher/" target="_blank" title="Instagram"><div class="link-image instagram"></div>Instagram</a>'
           ]
  contacts = ['<h4 class="contact-link">Mail</h4><a href="mailto:mail@christianmahnke.de" title="E-Mail senden">mail@christianmahnke.de</a>']
  disableScale = true
  description = "Pers√∂nliche Homepage von Christian Mahnke"
  debug = false
  pagetheme = "#701611"

[params.preview]
    outputPrefix = "ogPreview"
    outputSuffix = ".png"
    format =  "svg"
    image = "front.png"
    source = "post"
    [params.preview.size]
        height = 630
        width = 1200
    [params.preview.svg]
        template = "./Source Files/Other/preview-template.svg"
        scale = "width"
        removeMissing = true

[params.activitypub]
    author = "cmahnke"
    icon = "images/logo.png"
    image = ""
    outbox = "outbox.json"
    links = { "GitHub" = "", "Blog" = "" }

[languages.de.params]

[languages.en.params]
    subTitle = "Enthusiast & collector"
    contacts = ['<h4 class="contact-link">Mail</h4><a href="mailto:mail@christianmahnke.de" title="Send eMail">mail@christianmahnke.de</a>']
