name: Backup Mastodon

on:
  workflow_dispatch:
  schedule:
    - cron:  '30 3 * * 1,3,6'

env:
  #MASTODON_URL: https://openbiblio.social
  MASTODON_USER: cmahnke@openbiblio.social
  SECRET_FILE: ./openbiblio.social.user.cmahnke.secret
  BACKUP_BRANCH: mastodon-backup
  BACKUP_DIRECTORY: ./data/mastodon

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  backup:
    runs-on: ubuntu-24.04
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v6

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.x'

      - name: Install mastodon-archive
        run: pip install mastodon-archive

      - name: Setup Secret
        working-directory: ${{ env.BACKUP_DIRECTORY }}
        run: echo "${{ secrets.MASTODON_SECRET }}" > ${{ env.SECRET_FILE }}

      - name: Run backup
        working-directory: ${{ env.BACKUP_DIRECTORY }}
        run: mastodon-archive archive ${{ env.MASTODON_USER }}

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v7
        with:
          commit_message: Update Mastodon backup
          file_pattern: ${{ env.BACKUP_DIRECTORY }}/*.json
          branch: ${{ env.BACKUP_BRANCH }}
          create_branch: true